name: Compilar OPL Next ELF

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Compilar ELF para PS2 usando PS2SDK
        uses: addnab/docker-run-action@v3
        with:
          image: ps2dev/ps2dev:latest
          options: -v ${{ github.workspace }}:/src -w /src
          run: |
            make

      - name: Salvar o Arquivo .ELF
        uses: actions/upload-artifact@v3
        with:
          name: OPL_NEXT_BETA_ELF
          path: OPL_NEXT_BETA.ELF
