name: Compilar OPL Next ELF

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build PS2 ELF
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ps2dev/ps2dev:latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verificar PS2DEV
        run: |
          echo "PS2DEV=$PS2DEV"
          echo "PS2SDK=$PS2SDK"
          echo "PATH=$PATH"

          which mips64r5900el-ps2-elf-gcc
          mips64r5900el-ps2-elf-gcc --version

      - name: Build ELF
        run: |
          make clean
          make

      - name: Verificar ELF
        run: |
          ls -lh OPL_NEXT_BETA.ELF
          file OPL_NEXT_BETA.ELF

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OPL_NEXT_BETA_ELF
          path: OPL_NEXT_BETA.ELF